name: Blog markdown to hexo

on:
  push:
    branches:
      - main

env:
  GIT_USER: howard1209a
  GIT_EMAIL: howard1209a@gmail.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      # - name: Using cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.deploy_git
      #     key: deployGit
      #     restore-keys: deployGit

      # - name: Check if cached
      #   run: |
      #     tree .. -d -a

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      # - name: Install Python
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.7

      # - name: Install requirements
      #   run: |
      #     pip install requests

      # - name: Use python to debug
      #   env:
      #     GITHUBLEETCODEDEPLOYKEY: ${{ secrets.GITHUBLEETCODEDEPLOYKEY }}
      #     FORPYTHONDEBUG: ${{ secrets.FORPYTHONDEBUG }}
      #   run: |
      #     python debug.py

      - name: Config environment
        env:
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAv8wCCL9H+YmTwXkYEIB+shTGbXWM5qUIg2aGd92IWYQrsy8hDcchvBqARU14AVfPGaQOxD/zhHj+w8ZSj1Hael1vHvlttQz1wObe4VwN6W3nTYGi7GjFPbLsg1KMjhho7irvrXcuWCAW8X1TncsQoyLzPWK5I1d4BKhq+o9jclRYL+DjMu2WbJRcfss/WGcQ9/QU+2t+ESVcjolrgVJTi24zVQ6pFj1rMWJxe/vtJsi4apk2niQZUbimZLeEpUZFrtiltgG6bpMwabJtnrI2dpNvGTgx9GK4sB9p/piptXs/m9kECbo4iD/2aNjiE25TTYfh3nnwgZ4JVgTXRzI+ZR2SllD/XaK3VkO7jGHVl1vrDok5giA7GNkYZTevtA+Ry8/NRvARrX/tajH1+PsYoqJpedo6ezPeh/AEWSmFpJP+vC9zevD+Ucyh+wO8qyCfe+SeuTpilnq35L7bWyvQpr02OM37uUBp7cyAQpB1etwIdlh5lUkcxv/5AZuEfHPvAAAFkH/gyWp/4MlqAAAAB3NzaC1yc2EAAAGBAL/MAgi/R/mJk8F5GBCAfrIUxm11jOalCINmhnfdiFmEK7MvIQ3HIbwagEVNeAFXzxmkDsQ/84R4/sPGUo9R2npdbx75bbUM9cDm3uFcDelt502BouxoxT2y7INSjI4YaO4q7613LlggFvF9U53LEKMi8z1iuSNXeASoavqPY3JUWC/g4zLtlmyUXH7LP1hnEPf0FPtrfhElXI6Ja4FSU4tuM1UOqRY9azFicXv77SbIuGqZNp4kGVG4pmS3hKVGRa7YpbYBum6TMGmybZ6yNnaTbxk4MfRiuLAfaf6YqbV7P5vZBAm6OIg/9mjY4hNuU02H4d558IGeCVYE10cyPmUdkpZQ/12it1ZDu4xh1Zdb6w6JOYIgOxjZGGU3r7QPkcvPzUbwEa1/7Wox9fj7GKKiaXnaOnsz3ofwBFkphaST/rwvc3rw/lHMofsDvKsgn3vknrk6YpZ6t+S+21sr0Ka9NjjN+7lAae3MgEKQdXrcCHZYeZVJHMb/+QGbhHxz7wAAAAMBAAEAAAGAObeg3RUDCdsW9eAFF+IzPk/2LrZzQm1jlHdj++pUv+uAYxnJrqXARyUKeNCJTo4oKqUuNGyyUak/sZaa/bo6Lxyy9fVFyHgv9G8Fn3feT+Lc+nwKlW4p/Rk9B3/uAEzkNtgA7IizD54IiX+XjCKxzQYVgOGWqUYHPg+YsfI4kQ1ExJO+i3LoE6DJ/PYZB/dsKdHwBoEgnPRLWDGOgopNzeXJ2MzioWi2O1ROpmr3wPYiWSHmR8zBOdCBckmvxzTP+g7KVWrkYRsh7NB+sIRdefHdI0uoqKim/xt/zQLJc/a7DTCLu7V5CxYZg7zIv6SfEWdJqxXBwjFcJjcDqXvA/lfBgz58vEtYE8LGWDBav7r6OCwcWa+IMUVfF59vSBpmz/usUW/XN8H7OFnVp9cZ9/oz8KbkwDjwids+QpzWvc7vGJqdCqaJC4Bq7WxrSZLHitHRRXyfhooLux3KBq9XiJhS7LvxgNilVn5M6OpFvB4hMdyldylXNvTz1NFKwcSxAAAAwETNXo5PyjZ1hw6HCV//ALk+oyYS03Rzrg4YR6yR8HDeUl/gAmFXUOXy1Q1zTahofafVDnsySqTUW6YXc5WlbWkj/DLqMnWZ7t81AdvDGx4naYDvHz4GqlUbU/GtaVDqXhrIm4X6BK2P8SyCEivHnGNG5Zi6a614QPie6EXSIyxpffA8DL3Lh49f2Ii12xVwsTcFhNgoJE83x/Ir68f3S5uLs6xqD2OsmHNc+Z3pNLftnw83pRybo8zHsAmE+cW5QQAAAMEA5UJ7g+J5ygTrWpsWOSlRLszf+3LYTRiTaXlg+vNLlELXMRp8TViQxloD+YrO2shn89/vFf9SECXxpZdwpdOboelXp2mYCBxRsTAp6AJvC7SXGclD8XiTR0cE/U7/VPEk52UrU7KJt+i/uMTAdSoft9y/hbuiWimpULfCl5kMbo3MZU0znRRqbOuvMOYAXsPwLHpSmIbnIDp6VdecU1NL5TJ9/0/9GFdBlX3dnAa6r/IaVY3GfrryLoKHkchzl/5NAAAAwQDWKupa9/NOMLgrifBlkq7WIKe2Tnnd5O2/spamabQg2sD/Fv4qfeQVS64HsPrJXLNTjPYMojlnfFHY1VLkxYnWvimAIQLUV72V+2yIEPXtHT4o8+0UGKOGUNTacP9nA9sDYawWITMFSALadP9JckuqkZZk20+8V3vEWIZSEvyxwgL+J0IOkdch1346MplNm3g5+tijDUsvg18plZWhQbWJi9DzmCJXJ29v272Hu6t/IsR2BfoX8l7TNheqyv9oMSsAAAAVaG93YXJkMTIwOWFAZ21haWwuY29tAQIDBAUG: ${{ secrets.GITHUBLEETCODEDEPLOYKEY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "${{ secrets.GITHUBLEETCODEDEPLOYKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install hexo and init
        run: |
          npm install -g hexo-cli --save
          hexo init ../hexoWorkspace
          rm -f ../hexoWorkspace/source/_posts/hello-world.md  # 不再显示Hello World这篇文章（每次都显示在首页）
          sed -i 's/"<em>" + text + "<\/em>"/"_" + text + "_"/g' ../hexoWorkspace/node_modules/marked/lib/*
          # cat ../hexoWorkspace/node_modules/marked/lib/*

      - name: Copy config files from branch web_static
        run: |
          cp -r leetcode/note ../Articles

          # echo --- > ../Articles/README.md
          # echo title: README >> ../Articles/README.md
          # echo date: 9999-12-31 14:53:21 >> ../Articles/README.md
          # echo tags: README >> ../Articles/README.md
          # echo top: true >> ../Articles/README.md
          # echo --- >> ../Articles/README.md
          # cat README.md >> ../Articles/README.md

          git checkout web_static
          cp -r ToCopy ../staticFiles
          # rm -rf ../staticFiles/source/_posts  # 删除了 branch website_Static 的 ToCopy/source/_posts
          mv ../Articles ../staticFiles/source/_posts
          # mv -f ../staticFiles/* ../hexoWorkspace
          rsync -a ../staticFiles/* ../hexoWorkspace
          # echo tree ../hexoWorkspace/source/_posts

      - name: Install dependencies
        run: |
          cd ../hexoWorkspace
          npm install hexo-deployer-git --save
          npm install lodash --save
          npm install css --save     # 主题fluid需要使用
          # npm uninstall hexo-renderer-marked --save
          # sudo apt-get install pandoc
          # npm install hexo-renderer-pandoc --save
          # cd ../LeetCode

      - name: Deploy hexo
        run: |
          cd ../hexoWorkspace
          echo hexo g:
          hexo g
          echo hexo d:
          hexo d
          # cd ../LeetCode

      # - name: Move cache dir to other place
      #   run: |
      #     mv ../hexoWorkspace/.deploy_git ..
      #     tree .. -d -a

      # - name: Using cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.deploy_git
      #     key: deployGit
      #     restore-keys: deployGit

      # - name: Try to keep logs
      #   run: |
      #     echo tree -d -a ..
      #     tree -d -a ..
      #     mv .deploy_git/.git .deploy_git/git
      #     rsync -a .deploy_git/* ../LeetCode/.deploy_git
      #     echo git config --list
      #     git config --list
      #     echo git remote -v
      #     git remote -v
      #     git add .
      #     git commit -m "backup .deploy_git"
      #     git push origin website_Static
      #     echo cat .git/config
      #     cat .git/config
      #     echo ssh -T git@github.com
      #     ssh -T git@github.com

      # - name: Push to branch website_Static
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.WORKFLOWTOKEN }}
      #     # branch: ${{ github.ref }}
      #     # branch: website_Static
      #     branch: refs/heads/website_Static

      # - name: Push to branch website_Static
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     author_name: LetMeFly
      #     author_email: 814114971@qq.com
      #     message: "backup .deploy_git"
      #     add: "."
