name: Blog markdown to hexo

on:
  push:
    branches:
      - main

env:
  GIT_USER: howard1209a
  GIT_EMAIL: howard1209a@gmail.com

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Config environment
        env:
          GITHUBLEETCODEDEPLOYKEY: ${{ secrets.GITHUBLEETCODEDEPLOYKEY }}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "${{ secrets.GITHUBLEETCODEDEPLOYKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Install hexo and init
        run: |
          npm install -g hexo-cli --save
          hexo init ../hexoWorkspace
          rm -f ../hexoWorkspace/source/_posts/hello-world.md  # 不再显示Hello World这篇文章（每次都显示在首页）
          sed -i 's/"<em>" + text + "<\/em>"/"_" + text + "_"/g' ../hexoWorkspace/node_modules/marked/lib/*

      - name: Copy config files from branch web_static
        run: |
          git checkout main
          cp -r leetcode/note ../Articles
          git checkout web_static
          cp -r ToCopy ../staticFiles
          mv ../Articles ../staticFiles/source/_posts
          rsync -a ../staticFiles/* ../hexoWorkspace

      - name: Install dependencies
        run: |
          cd ../hexoWorkspace
          npm install hexo-deployer-git --save
          npm install lodash --save
          npm install css --save     # 主题fluid需要使用
          cd ../notes

      - name: Deploy hexo
        run: |
          cd ../hexoWorkspace
          echo hexo g:
          hexo g
          echo hexo d:
          hexo d
          cd ../notes
