name: hexo-blog-deploy

on:
  push:
    branches:
      - main

env:
  GIT_USER: howard1209a
  GIT_EMAIL: howard1209a@gmail.com
  DEPLOY_REPO: howard1209a/notes
  DEPLOY_BRANCH: web

jobs:
  build:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [19.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout deploy repo
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_SECRET: ${{secrets.HEXO_DEPLOY_SECRET}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Install dependencies
        run: |
          npm install
          npm install hexo-deployer-git --save
          # 全局搜索插件
          npm install hexo-generator-searchdb --save

      - name: Deploy hexo
        run: |
          npm run deploy
